name: Repetition code
description: Device from DiCarlo lab used for the repetition code experiment
distance: 5
interaction_order:
- - 1
  - left
- - 1
  - right
- - 2
  - left
- - 2
  - right
layout:
- coords:
  - 4
  - 0
  freq_group: low
  neighbors:
    north_east: Z2
    north_west: null
    south_east: null
    south_west: null
  qubit: D3
  role: data
- coords:
  - 0
  - 2
  freq_group: high
  neighbors:
    north_east: null
    north_west: Z3
    south_east: Z1
    south_west: null
  qubit: D4
  role: data
- coords:
  - 2
  - 2
  freq_group: high
  neighbors:
    north_east: Z4
    north_west: null
    south_east: null
    south_west: Z1
  qubit: D5
  role: data
- coords:
  - 4
  - 2
  freq_group: high
  neighbors:
    north_east: null
    north_west: Z4
    south_east: Z2
    south_west: null
  qubit: D6
  role: data
- coords:
  - 0
  - 4
  freq_group: low
  neighbors:
    north_east: null
    north_west: null
    south_east: null
    south_west: Z3
  qubit: D7
  role: data
- coords:
  - 1
  - 1
  freq_group: mid
  group: 1
  neighbors:
    north_east: D5
    north_west: D4
    south_east: null
    south_west: null
  order:
    left: north_west
    right: north_east
  qubit: Z1
  role: anc
  stab_type: x_type
- coords:
  - 5
  - 1
  freq_group: mid
  group: 1
  neighbors:
    north_east: null
    north_west: D6
    south_east: null
    south_west: D3
  order:
    left: north_west
    right: south_west
  qubit: Z2
  role: anc
  stab_type: x_type
- coords:
  - -1
  - 3
  freq_group: mid
  group: 2
  neighbors:
    north_east: D7
    north_west: null
    south_east: D4
    south_west: null
  order:
    left: north_east
    right: south_east
  qubit: Z3
  role: anc
  stab_type: x_type
- coords:
  - 3
  - 3
  freq_group: mid
  group: 2
  neighbors:
    north_east: null
    north_west: null
    south_east: D6
    south_west: D5
  order:
    left: south_west
    right: south_east
  qubit: Z4
  role: anc
  stab_type: x_type